### Kmeans

![image info](./sse.png)
![image info](./sil.png)

In [4]:
#df

Classe           SSE  silhouette_score
0       2  5.434968e+25          0.357633
1       3  3.729277e+25          0.360811
2       4  2.205590e+25          0.383289
3       5  1.682335e+25          0.362750
4       6  1.232326e+25          0.394790
5       7  9.741232e+24          0.368860
6       8  8.061593e+24          0.345248
7       9  6.403752e+24          0.390632

### Let's consider 9 classes

In [8]:
#df9

Classe   Number
0       0     3916
1       1       77
2       2    25777
3       3       30
4       4        1
5       5      165
6       6  1645607
7       7    87350
8       8      687

##### First classe

In [26]:
df99[df99["classe"] == 0].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

     - il y a **3916** individus dans cette classe.
     - ils reçoivent au maximum **130** appels entrants internationals et émettent au maximum 1 appel sortant international. 
     - Ainsi cette classe peut etre considérer comme une classe de non-fraudeurs, d'individus normals.

#### Second classe

In [27]:
df99[df99["classe"] == 1].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

 - Dans cette classe, nous remarquons que les individus n'émettent pas d'appels internationals et en reçoivent très peu.
 - Idéalement, ils sont des individus normaux.

#### Third classe

In [28]:
df99[df99["classe"] == 2].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

 - Comparée aux 2 précédentes classes, cette classe-ci recoit beaucoup d'appels internationals entrants (maximum : 199).
 - Mais elle émet très peu d'appels internationals.
 - Elle est une classe de non-fraudeurs.

#### Fourth classe

In [29]:
df99[df99["classe"] == 3].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

 - Ici également, les individus n'emettent pas d'appels à l'international
 - Classe d'individus normaux

#### Fifth classe

In [30]:
df99[df99["classe"] == 4]

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py:345: UserWarning:
Lux defaults to Pandas when there are no valid actions defined.


nbre_call_entrant_inter  nbre_call_sortant_inter  duree_entrant_inter  \
msisdn                                                                          
NaN                         0.0                      0.0                  0.0   

        duree_sortant_inter  duree_total_inter  duree_moy_sortant_inter  \
msisdn                                                                    
NaN                     0.0                0.0                      0.0   

        duree_moy_inter  nbr_cor_dist  nbr_appel_abs_entr_moy  \
msisdn                                                          
NaN                 0.0           0.0                     0.0   

        nbr_appel_abs_entr_med  ...  temp_appel_moy  ecartyp_temp_appel  \
msisdn                          ...                                       
NaN                        0.0  ...             0.0                 0.0   

        ratio_call_dist  ratio_dist_sms  taux_call_night  taux_call_on  \
msisdn                                                                   
NaN                 0.0             0.0              0.0           0.0   

        taux_call_inter  nbre_transaction  nbre_distinct_msisdn  classe  
msisdn                                                                   
NaN                 0.0               0.0                   0.0       4  

[1 rows x 91 columns]

 - l'individu est une valeur manquante

#### Sixth classe

In [31]:
df99[df99["classe"] == 5].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

 - Elle émet très peu d'appels internationals et en reçoit très peu.
 - Classe d'individus normals

#### Seventh classe

In [32]:
df99[df99["classe"] == 6].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

 - On a **1645607** indivdus pour cette classe
 - Egalement on remarque qu'il y des individus émettant très peu d'appels internationals et d'autres émettant beaucoup (max : 502) 
 - Classe Hétérogène

#### Eighth classe

In [33]:
df99[df99["classe"] == 7].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

 - Très peu d'appels internationals émis.
 - Classe d'individus normals

#### Nineth classe

In [34]:
df99[df99["classe"] == 8].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

 - Très peu d'appels internationals émis et reçus
 - Classe d'individus normals

#### Let's deep in sixth classe

In [69]:
#df6 = df99[df99["classe"] == 6]

In [76]:
#df66 = df6[df6["nbre_call_sortant_inter"] > 7]

In [77]:
#df66.describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [6]:
import pandas as pd
data = {'Classe':  list(range(2,10)) ,
        'SSE': [5.434967701817736e+25,
 3.7292770396258056e+25,
 2.2055902154519345e+25,
 1.6823347142867633e+25,
 1.2323264279178966e+25,
 9.74123207562669e+24,
 8.061592516466469e+24,
 6.403752110130262e+24],
          "silhouette_score" : [0.35763347707327836,
0.36081141426559715,
0.3832894071596234,
0.3627498855197289,
0.39478999960818756,
0.36885963285553164,
0.34524785939189306,
0.39063168331289955]
        }

df = pd.DataFrame (data, columns = ['Classe','SSE', 'silhouette_score'])

In [7]:
import pandas as pd
data9 = {'Classe':  [0, 1, 2, 3, 4, 5, 6, 7, 8] ,
        'Number': [   3916,      77,   25777,      30,       1,     165, 1645607,
          87350,     687]
        }

df9 = pd.DataFrame (data9 , columns = ['Classe','Number'])

In [3]:
from sklearn.metrics import *
import pandas as pd
import lux

## MAIN KMEANS 

In [10]:
import matplotlib.pyplot as plt
from kneed import KneeLocator
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [11]:
df = pd.read_csv("ech_data.csv", sep = ";")

In [12]:
df9 = df[[
 'nbre_call_entrant_inter',
 'nbre_call_sortant_inter',
 'duree_entrant_inter',
 'duree_sortant_inter',
 'duree_total_inter',
 'duree_moy_sortant_inter',
 'duree_moy_inter',
 'nbr_cor_dist',
 'nbr_appel_abs_entr_moy',
 'nbr_appel_abs_entr_med',
 'nbr_appel_abs_entr_tot',
 'nbr_entrant_distinct_absence_tot',
 'nbr_entrant_distinct_absence_med',
 'nbr_appel_abs_sort_moy',
 'nbr_appel_abs_sort_med',
 'nbr_appel_abs_sort_tot',
 'nbre_transaction_tot',
 'nbre_transaction_med',
 'nbre_distinct_msisdn_tot',
 'nbre_distinct_msisdn_med',
 'duree_tot',
 'duree_med',
 'nbre_distinct_imei_x',
 'nombre_transaction_erecharge',
 'montant_erecharge',
 'nbre_imsi',
 'montant',
 'montant_moy',
 'nbr_om_transact',
 'volumepartage_data_med',
 'nbr_partage_data',
 'total_partage_data',
 'nombre_distinct_profil',
 'nbr_sms_total_sortant_ofnet',
 'nbr_sms_sortant_med_ofnet',
 'nbr_sms_sortant_moy_ofnet',
 'nbr_appel_sortant_moy_ofnet',
 'nbr_appel_total_sortant_ofnet',
 'nbr_appel_sortant_med_ofnet',
 'duree_total_sortant_ofnet',
 'duree_sortant_med_ofnet',
 'duree_sortant_moy_ofnet',
 'nbr_sms_total_sortant_onnet',
 'nbr_sms_sortant_med_onnet',
 'nbr_sms_sortant_moy_onnet',
 'nbr_appel_sortant_moy_onnet',
 'nbr_appel_total_sortant_onnet',
 'nbr_appel_sortant_med_onnet',
 'duree_total_sortant_onnet',
 'duree_sortant_med_onnet',
 'duree_sortant_moy_onnet',
 'nbr_rech_sos',
 'nbr_moy_sos',
 'montant_tot_sos',
 'montant_moy_sos',
 'nbr_corr_dist_entrant_sms_tot',
 'nbr_corr_dist_entrant_sms_med',
 'nbr_corr_dist_sortant_sms_tot',
 'nbr_corr_dist_sortant_sms_med',
 'nbr_duree_data_tot',
 'nbr_duree_data_med',
 'nbr_duree_data_moy',
 'volume_family_data_med',
 'nbr_family_data',
 'family_data_tot',
 'nbre_call_complice',
 'duree_x',
 'duree_moy_call_complice',
 'volume_data_total',
 'volume_data_moy',
 'volume_data_med',
 'nbre_corr_sortant',
 'nbre_corr_sortant_distinc',
 'nbre_corr_entrant',
 'nbre_corr_entrant_distinct',
 'temp_sms_moy',
 'ecartyp_temp_sms',
 'nbre_distinct_imei_y',
 'nbr_achat_pass',
 'montant_pass_med',
 'mnt_tot_pass',
 'temp_appel_moy',
 'ecartyp_temp_appel',
 'ratio_call_dist',
 'ratio_dist_sms',
 'taux_call_night',
 'taux_call_on',
 'taux_call_inter',
 'nbre_transaction',
 'nbre_distinct_msisdn']]

In [13]:
df91 = df9.fillna(0)

In [14]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df91)

In [15]:
kmeans_kwargs = {
"init": "random",
"n_init": 10,
"max_iter": 300,
"random_state": 42 }

In [16]:
kmeans = KMeans(n_clusters=9, **kmeans_kwargs)
kmeans.fit(df91)
print(kmeans.inertia_)

6.403752110130261e+24


In [8]:
yhat = kmeans.predict(df91)

In [9]:
from numpy import unique
clusters = unique(yhat, return_counts = True)
clusters

(array([0, 1, 2], dtype=int32), array([      1,     666, 1762943]))

In [27]:
df91["classe"] = yhat

## MAIN KMEANS 

In [13]:
df91[df91["classe"] == 1].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

## FRAUDEURS

In [19]:
fraudeurs = pd.read_csv("fraudeur3.csv", sep = ",")
fraudeurs.head()
#fraudeurs.shape

msisdn  mnt_med_pass_sva  mnt_tot_pass_sva  nbr_achat_pass_sva  \
0  97412290               NaN               NaN                 NaN   
1  68912429               NaN               NaN                 NaN   
2  67442397             103.0             103.0                 1.0   
3  79323879               NaN               NaN                 NaN   
4  97424091             150.0             150.0                 3.0   

   mnt_med_mix  mnt_tot_mix  nbr_achat_pass_mix  mnt_pass_med_inter  \
0          NaN          NaN                 NaN                 NaN   
1          NaN          NaN                 NaN                 NaN   
2        450.0       4200.0                21.0                 NaN   
3        600.0       3500.0                14.0                 NaN   
4        300.0       2100.0                 9.0                 NaN   

   mnt_tot_inter_pass  nbr_achat_pass_inter  ...  nbr_call_en_of_y  \
0                 NaN                   NaN  ...               0.0   
1                 NaN                   NaN  ...               0.0   
2                 NaN                   NaN  ...               0.0   
3                 NaN                   NaN  ...               0.0   
4                 NaN                   NaN  ...               0.0   

   duree_call_tot_en_of_y  duree_call_moy_en_of_y  duree_data_tot  \
0                     4.0                1.333333             NaN   
1                     5.0                1.250000             NaN   
2                    14.0                2.000000             NaN   
3                     8.0                2.666667      905.444444   
4                    25.0                3.125000     6962.263158   

   vol_tot_data  nbr_call_tot_complice  duree_call_moy_complice  \
0           NaN                    NaN                      NaN   
1           NaN                    NaN                      NaN   
2           NaN                    NaN                      NaN   
3       23910.0                    NaN                      NaN   
4   570059041.0                    NaN                      NaN   

   duree_call_tot_complice  nbr_call_sort_abs  nbr_call_en_abs  
0                      NaN                NaN              NaN  
1                      NaN                NaN              NaN  
2                      NaN                NaN              NaN  
3                      NaN                NaN              NaN  
4                      NaN                NaN              NaN  

[5 rows x 69 columns]

In [20]:
fraudeurs.describe()

msisdn  mnt_med_pass_sva  mnt_tot_pass_sva  nbr_achat_pass_sva  \
count  1.670000e+02         13.000000         13.000000           13.000000   
mean   7.366836e+07        396.615385        904.307692            2.230769   
std    1.824344e+07        385.007476       1731.032369            2.166174   
min    9.753285e+06         50.000000         50.000000            1.000000   
25%    5.917396e+07        103.000000        103.000000            1.000000   
50%    7.709993e+07        150.000000        150.000000            2.000000   
75%    8.887767e+07        500.000000       1000.000000            2.000000   
max    9.842885e+07       1000.000000       6500.000000            9.000000   

       mnt_med_mix   mnt_tot_mix  nbr_achat_pass_mix  mnt_pass_med_inter  \
count    71.000000     71.000000           71.000000           10.000000   
mean    498.239437   4018.309859           15.718310         2100.000000   
std     242.506404   6056.792170           23.850237          210.818511   
min     150.000000    150.000000            1.000000         2000.000000   
25%     300.000000   1000.000000            1.000000         2000.000000   
50%     450.000000   3300.000000           12.000000         2000.000000   
75%     525.000000   3900.000000           16.000000         2000.000000   
max    1175.000000  45050.000000          172.000000         2500.000000   

       mnt_tot_inter_pass  nbr_achat_pass_inter  ...  nbr_call_en_of_y  \
count           10.000000             10.000000  ...        157.000000   
mean          2600.000000              1.400000  ...          0.579618   
std           1264.911064              0.843274  ...          1.349869   
min           2000.000000              1.000000  ...          0.000000   
25%           2000.000000              1.000000  ...          0.000000   
50%           2000.000000              1.000000  ...          0.000000   
75%           2000.000000              1.000000  ...          0.000000   
max           5000.000000              3.000000  ...         10.000000   

       duree_call_tot_en_of_y  duree_call_moy_en_of_y  duree_data_tot  \
count              157.000000              157.000000       23.000000   
mean                24.968153                4.936728     3129.918784   
std                 36.564909                5.086854     3087.563691   
min                  1.000000                1.000000        4.500000   
25%                  5.000000                1.750000      905.558442   
50%                 12.000000                3.000000     2595.500000   
75%                 27.000000                5.500000     4746.797619   
max                265.000000               29.750000     9287.400000   

       vol_tot_data  nbr_call_tot_complice  duree_call_moy_complice  \
count  2.300000e+01                    0.0                      0.0   
mean   2.190473e+08                    NaN                      NaN   
std    2.529957e+08                    NaN                      NaN   
min    2.810000e+03                    NaN                      NaN   
25%    2.208100e+04                    NaN                      NaN   
50%    1.062430e+08                    NaN                      NaN   
75%    4.412539e+08                    NaN                      NaN   
max    7.987241e+08                    NaN                      NaN   

       duree_call_tot_complice  nbr_call_sort_abs  nbr_call_en_abs  
count                      0.0          41.000000        10.000000  
mean                       NaN           1.707317         1.200000  
std                        NaN           1.749913         0.632456  
min                        NaN           1.000000         1.000000  
25%                        NaN           1.000000         1.000000  
50%                        NaN           1.000000         1.000000  
75%                        NaN           1.000000         1.000000  
max                        NaN           8.000000         3.000000  

[8 rows x 69 columns]

In [21]:
fraudeurs1 = fraudeurs.copy()

In [22]:
fraudeurs1 = fraudeurs1.fillna(0)

In [23]:
fraudeurs1.describe()

msisdn  mnt_med_pass_sva  mnt_tot_pass_sva  nbr_achat_pass_sva  \
count  1.670000e+02        167.000000        167.000000          167.000000   
mean   7.366836e+07         30.874251         70.395210            0.173653   
std    1.824344e+07        148.578209        525.042465            0.835810   
min    9.753285e+06          0.000000          0.000000            0.000000   
25%    5.917396e+07          0.000000          0.000000            0.000000   
50%    7.709993e+07          0.000000          0.000000            0.000000   
75%    8.887767e+07          0.000000          0.000000            0.000000   
max    9.842885e+07       1000.000000       6500.000000            9.000000   

       mnt_med_mix   mnt_tot_mix  nbr_achat_pass_mix  mnt_pass_med_inter  \
count   167.000000    167.000000          167.000000          167.000000   
mean    211.826347   1708.383234            6.682635          125.748503   
std     292.975162   4409.022283           17.338268          502.159682   
min       0.000000      0.000000            0.000000            0.000000   
25%       0.000000      0.000000            0.000000            0.000000   
50%       0.000000      0.000000            0.000000            0.000000   
75%     450.000000   2825.000000           10.500000            0.000000   
max    1175.000000  45050.000000          172.000000         2500.000000   

       mnt_tot_inter_pass  nbr_achat_pass_inter  ...  nbr_call_en_of_y  \
count          167.000000            167.000000  ...        167.000000   
mean           155.688623              0.083832  ...          0.544910   
std            685.267056              0.386725  ...          1.315829   
min              0.000000              0.000000  ...          0.000000   
25%              0.000000              0.000000  ...          0.000000   
50%              0.000000              0.000000  ...          0.000000   
75%              0.000000              0.000000  ...          0.000000   
max           5000.000000              3.000000  ...         10.000000   

       duree_call_tot_en_of_y  duree_call_moy_en_of_y  duree_data_tot  \
count              167.000000              167.000000      167.000000   
mean                23.473054                4.641115      431.066659   
std                 35.941018                5.069272     1560.067216   
min                  0.000000                0.000000        0.000000   
25%                  5.000000                1.666667        0.000000   
50%                 10.000000                2.666667        0.000000   
75%                 25.000000                5.000000        0.000000   
max                265.000000               29.750000     9287.400000   

       vol_tot_data  nbr_call_tot_complice  duree_call_moy_complice  \
count  1.670000e+02                  167.0                    167.0   
mean   3.016819e+07                    0.0                      0.0   
std    1.192279e+08                    0.0                      0.0   
min    0.000000e+00                    0.0                      0.0   
25%    0.000000e+00                    0.0                      0.0   
50%    0.000000e+00                    0.0                      0.0   
75%    0.000000e+00                    0.0                      0.0   
max    7.987241e+08                    0.0                      0.0   

       duree_call_tot_complice  nbr_call_sort_abs  nbr_call_en_abs  
count                    167.0         167.000000       167.000000  
mean                       0.0           0.419162         0.071856  
std                        0.0           1.131846         0.321309  
min                        0.0           0.000000         0.000000  
25%                        0.0           0.000000         0.000000  
50%                        0.0           0.000000         0.000000  
75%                        0.0           0.000000         0.000000  
max                        0.0           8.000000         3.000000  

[8 rows x 69 columns]

In [29]:
#df91.columns

## FRAUDEURS

## NON FRAUDEURS AMONG df91["classe"] 

In [36]:
df91["msisdn"] = df["msisdn"]

In [37]:
df6 = df91[df91["classe"] == 6]

In [38]:
def anti_join(x, y, on):
    """Return rows in x which are not present in y"""
    ans = pd.merge(left=x, right=y, how='left', indicator=True, on=on)
    ans = ans.loc[ans._merge == 'left_only', :].drop(columns='_merge')
    return ans

In [39]:
#df_anti = pd.merge(df6[["msisdn"]] ,fraudeurs, on='msisdn', how='anti')

In [48]:
df_anti = anti_join(df6["msisdn"] ,fraudeurs, "msisdn")

In [57]:
fraudeurs.columns

Index(['msisdn', 'mnt_med_pass_sva', 'mnt_tot_pass_sva', 'nbr_achat_pass_sva',
       'mnt_med_mix', 'mnt_tot_mix', 'nbr_achat_pass_mix',
       'mnt_pass_med_inter', 'mnt_tot_inter_pass', 'nbr_achat_pass_inter',
       'mnt_med_pass_data', 'mnt_tot_pass_data', 'nbr_achat_pass_data',
       'nbr_transac_share', 'vol_tot_data_share', 'vol_moy_data_share',
       'nbr_transac_family', 'vol_tot_data_family', 'vol_moy_data_family',
       'nbr_rechar', 'mnt_rechar_tot', 'mnt_rechar_moy', 'temp_sms_moy',
       'ecartyp_temp_sms', 'nbr_dist_en_of_x', 'nbr_call_en_of_x',
       'duree_call_tot_en_of_x', 'duree_call_moy_en_of_x', 'nbr_dist_sort_on',
       'nbr_call_sort_on', 'duree_call_tot_sort_on', 'duree_call_moy_sort_on',
       'nbr_dist_sort_of', 'nbr_call_sort_of', 'duree_call_tot_sort_of',
       'duree_call_moy_sort_of', 'nbr_sms_tot_sort_inter',
       'nbr_call_tot_sort_inter', 'duree_call_tot_sort_inter',
       'duree_call_moy_sort_inter', 'nbr_call_sort_night',
       'duree_mo

In [50]:
df_anti.columns

Index(['msisdn', 'mnt_med_pass_sva', 'mnt_tot_pass_sva', 'nbr_achat_pass_sva',
       'mnt_med_mix', 'mnt_tot_mix', 'nbr_achat_pass_mix',
       'mnt_pass_med_inter', 'mnt_tot_inter_pass', 'nbr_achat_pass_inter',
       'mnt_med_pass_data', 'mnt_tot_pass_data', 'nbr_achat_pass_data',
       'nbr_transac_share', 'vol_tot_data_share', 'vol_moy_data_share',
       'nbr_transac_family', 'vol_tot_data_family', 'vol_moy_data_family',
       'nbr_rechar', 'mnt_rechar_tot', 'mnt_rechar_moy', 'temp_sms_moy',
       'ecartyp_temp_sms', 'nbr_dist_en_of_x', 'nbr_call_en_of_x',
       'duree_call_tot_en_of_x', 'duree_call_moy_en_of_x', 'nbr_dist_sort_on',
       'nbr_call_sort_on', 'duree_call_tot_sort_on', 'duree_call_moy_sort_on',
       'nbr_dist_sort_of', 'nbr_call_sort_of', 'duree_call_tot_sort_of',
       'duree_call_moy_sort_of', 'nbr_sms_tot_sort_inter',
       'nbr_call_tot_sort_inter', 'duree_call_tot_sort_inter',
       'duree_call_moy_sort_inter', 'nbr_call_sort_night',
       'duree_mo

In [46]:
anti_join(df6["msisdn"] ,fraudeurs, "msisdn").shape

(1645440, 69)

In [35]:
df6[["msisdn"]].head()

KeyError: "None of [Index(['msisdn'], dtype='object')] are in the [columns]"

In [42]:
pd.merge(df["msisdn"] ,fraudeurs, on='msisdn', how='inner').head()

msisdn  mnt_med_pass_sva  mnt_tot_pass_sva  nbr_achat_pass_sva  \
0  48531591.0               NaN               NaN                 NaN   
1  67442397.0             103.0             103.0                 1.0   
2  97648507.0               NaN               NaN                 NaN   
3  87700364.0               NaN               NaN                 NaN   
4  89280762.0               NaN               NaN                 NaN   

   mnt_med_mix  mnt_tot_mix  nbr_achat_pass_mix  mnt_pass_med_inter  \
0        500.0       4500.0                12.0                 NaN   
1        450.0       4200.0                21.0                 NaN   
2          NaN          NaN                 NaN                 NaN   
3          NaN          NaN                 NaN              2000.0   
4        550.0       4550.0                16.0                 NaN   

   mnt_tot_inter_pass  nbr_achat_pass_inter  ...  nbr_call_en_of_y  \
0                 NaN                   NaN  ...               0.0   
1                 NaN                   NaN  ...               0.0   
2                 NaN                   NaN  ...               0.0   
3              2000.0                   1.0  ...               0.0   
4                 NaN                   NaN  ...               0.0   

   duree_call_tot_en_of_y  duree_call_moy_en_of_y  duree_data_tot  \
0                    33.0                5.500000             NaN   
1                    14.0                2.000000             NaN   
2                     4.0                1.333333             NaN   
3                    19.0                1.727273             NaN   
4                     6.0                1.500000             NaN   

   vol_tot_data  nbr_call_tot_complice  duree_call_moy_complice  \
0           NaN                    NaN                      NaN   
1           NaN                    NaN                      NaN   
2           NaN                    NaN                      NaN   
3           NaN                    NaN                      NaN   
4           NaN                    NaN                      NaN   

   duree_call_tot_complice  nbr_call_sort_abs  nbr_call_en_abs  
0                      NaN                NaN              NaN  
1                      NaN                NaN              NaN  
2                      NaN                NaN              NaN  
3                      NaN                NaN              NaN  
4                      NaN                NaN              NaN  

[5 rows x 69 columns]

In [44]:
pd.merge(df6["msisdn"] ,fraudeurs, on='msisdn', how='inner').shape

(167, 69)

In [47]:
1645440 + 167

1645607

In [53]:
df_anti1 = df_anti.fillna(0)

## KMEANS ON 6 

In [75]:
#df6.columns

In [76]:
df61 = df6[['nbre_call_entrant_inter', 'nbre_call_sortant_inter',
       'duree_entrant_inter', 'duree_sortant_inter', 'duree_total_inter',
       'duree_moy_sortant_inter', 'duree_moy_inter', 'nbr_cor_dist',
       'nbr_appel_abs_entr_moy', 'nbr_appel_abs_entr_med',
       'nbr_appel_abs_entr_tot', 'nbr_entrant_distinct_absence_tot',
       'nbr_entrant_distinct_absence_med', 'nbr_appel_abs_sort_moy',
       'nbr_appel_abs_sort_med', 'nbr_appel_abs_sort_tot',
       'nbre_transaction_tot', 'nbre_transaction_med',
       'nbre_distinct_msisdn_tot', 'nbre_distinct_msisdn_med', 'duree_tot',
       'duree_med', 'nbre_distinct_imei_x', 'nombre_transaction_erecharge',
       'montant_erecharge', 'nbre_imsi', 'montant', 'montant_moy',
       'nbr_om_transact', 'volumepartage_data_med', 'nbr_partage_data',
       'total_partage_data', 'nombre_distinct_profil',
       'nbr_sms_total_sortant_ofnet', 'nbr_sms_sortant_med_ofnet',
       'nbr_sms_sortant_moy_ofnet', 'nbr_appel_sortant_moy_ofnet',
       'nbr_appel_total_sortant_ofnet', 'nbr_appel_sortant_med_ofnet',
       'duree_total_sortant_ofnet', 'duree_sortant_med_ofnet',
       'duree_sortant_moy_ofnet', 'nbr_sms_total_sortant_onnet',
       'nbr_sms_sortant_med_onnet', 'nbr_sms_sortant_moy_onnet',
       'nbr_appel_sortant_moy_onnet', 'nbr_appel_total_sortant_onnet',
       'nbr_appel_sortant_med_onnet', 'duree_total_sortant_onnet',
       'duree_sortant_med_onnet', 'duree_sortant_moy_onnet', 'nbr_rech_sos',
       'nbr_moy_sos', 'montant_tot_sos', 'montant_moy_sos',
       'nbr_corr_dist_entrant_sms_tot', 'nbr_corr_dist_entrant_sms_med',
       'nbr_corr_dist_sortant_sms_tot', 'nbr_corr_dist_sortant_sms_med',
       'nbr_duree_data_tot', 'nbr_duree_data_med', 'nbr_duree_data_moy',
       'volume_family_data_med', 'nbr_family_data', 'family_data_tot',
       'nbre_call_complice', 'duree_x', 'duree_moy_call_complice',
       'volume_data_total', 'volume_data_moy', 'volume_data_med',
       'nbre_corr_sortant', 'nbre_corr_sortant_distinc', 'nbre_corr_entrant',
       'nbre_corr_entrant_distinct', 'temp_sms_moy', 'ecartyp_temp_sms',
       'nbre_distinct_imei_y', 'nbr_achat_pass', 'montant_pass_med',
       'mnt_tot_pass', 'temp_appel_moy', 'ecartyp_temp_appel',
       'ratio_call_dist', 'ratio_dist_sms', 'taux_call_night', 'taux_call_on',
       'taux_call_inter', 'nbre_transaction', 'nbre_distinct_msisdn']]

In [77]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df61)

kmeans_kwargs = {
"init": "random",
"n_init": 10,
"max_iter": 300,
"random_state": 42 }

kmeans = KMeans(n_clusters=9, **kmeans_kwargs)
kmeans.fit(df61)
print(kmeans.inertia_)

yhat6 = kmeans.predict(df61)

4.712151034811712e+22


In [78]:
clusters = unique(yhat6, return_counts = True)
clusters

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32),
 array([    170, 1482638,   49181,      41,      82,     137,   35574,
          77471,     313]))

In [80]:
df61["classe2"] = yhat6

<ipython-input-80-c92a4b8d3b51>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df61["classe2"] = yhat6


In [81]:
df61["msisdn"] = df6["msisdn"]

In [84]:
pd.merge(df61[df61["classe2"] == 1]["msisdn"] ,fraudeurs, on='msisdn', how='inner').shape

(167, 69)

## KMEANS ON 1

In [85]:
df6_1 = df61[df61["classe2"] == 1]

In [86]:
df6_11 = df6_1[['nbre_call_entrant_inter', 'nbre_call_sortant_inter',
       'duree_entrant_inter', 'duree_sortant_inter', 'duree_total_inter',
       'duree_moy_sortant_inter', 'duree_moy_inter', 'nbr_cor_dist',
       'nbr_appel_abs_entr_moy', 'nbr_appel_abs_entr_med',
       'nbr_appel_abs_entr_tot', 'nbr_entrant_distinct_absence_tot',
       'nbr_entrant_distinct_absence_med', 'nbr_appel_abs_sort_moy',
       'nbr_appel_abs_sort_med', 'nbr_appel_abs_sort_tot',
       'nbre_transaction_tot', 'nbre_transaction_med',
       'nbre_distinct_msisdn_tot', 'nbre_distinct_msisdn_med', 'duree_tot',
       'duree_med', 'nbre_distinct_imei_x', 'nombre_transaction_erecharge',
       'montant_erecharge', 'nbre_imsi', 'montant', 'montant_moy',
       'nbr_om_transact', 'volumepartage_data_med', 'nbr_partage_data',
       'total_partage_data', 'nombre_distinct_profil',
       'nbr_sms_total_sortant_ofnet', 'nbr_sms_sortant_med_ofnet',
       'nbr_sms_sortant_moy_ofnet', 'nbr_appel_sortant_moy_ofnet',
       'nbr_appel_total_sortant_ofnet', 'nbr_appel_sortant_med_ofnet',
       'duree_total_sortant_ofnet', 'duree_sortant_med_ofnet',
       'duree_sortant_moy_ofnet', 'nbr_sms_total_sortant_onnet',
       'nbr_sms_sortant_med_onnet', 'nbr_sms_sortant_moy_onnet',
       'nbr_appel_sortant_moy_onnet', 'nbr_appel_total_sortant_onnet',
       'nbr_appel_sortant_med_onnet', 'duree_total_sortant_onnet',
       'duree_sortant_med_onnet', 'duree_sortant_moy_onnet', 'nbr_rech_sos',
       'nbr_moy_sos', 'montant_tot_sos', 'montant_moy_sos',
       'nbr_corr_dist_entrant_sms_tot', 'nbr_corr_dist_entrant_sms_med',
       'nbr_corr_dist_sortant_sms_tot', 'nbr_corr_dist_sortant_sms_med',
       'nbr_duree_data_tot', 'nbr_duree_data_med', 'nbr_duree_data_moy',
       'volume_family_data_med', 'nbr_family_data', 'family_data_tot',
       'nbre_call_complice', 'duree_x', 'duree_moy_call_complice',
       'volume_data_total', 'volume_data_moy', 'volume_data_med',
       'nbre_corr_sortant', 'nbre_corr_sortant_distinc', 'nbre_corr_entrant',
       'nbre_corr_entrant_distinct', 'temp_sms_moy', 'ecartyp_temp_sms',
       'nbre_distinct_imei_y', 'nbr_achat_pass', 'montant_pass_med',
       'mnt_tot_pass', 'temp_appel_moy', 'ecartyp_temp_appel',
       'ratio_call_dist', 'ratio_dist_sms', 'taux_call_night', 'taux_call_on',
       'taux_call_inter', 'nbre_transaction', 'nbre_distinct_msisdn']]

In [ ]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df6_11)

kmeans_kwargs = {
"init": "random",
"n_init": 10,
"max_iter": 300,
"random_state": 42 }

kmeans = KMeans(n_clusters=1000, **kmeans_kwargs)
kmeans.fit(df6_11)
print(kmeans.inertia_)

yhat6_1 = kmeans.predict(df6_11)

clusters = unique(yhat6_1, return_counts = True)
clusters

In [92]:
1386400 - 1482638

-96238

In [93]:
96238*5

481190

In [96]:
1482638-96238*10 

520258

In [88]:
df6_11["classe3"] = yhat6_1

<ipython-input-88-d4a408b79ab3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6_11["classe3"] = yhat6_1


In [89]:
df6_11["msisdn"] = df61["msisdn"]

In [91]:
pd.merge(df6_11[df6_11["classe3"] == 22]["msisdn"] ,fraudeurs, on='msisdn', how='inner').shape

(167, 69)

## ISOLATION FOREST TO DETECT 

In [24]:
from sklearn.ensemble import IsolationForest

In [62]:
X = fraudeurs1[["mnt_med_pass_sva", 'mnt_tot_pass_sva', 'nbr_achat_pass_sva',
       'mnt_med_mix', 'mnt_tot_mix', 'nbr_achat_pass_mix',
       'mnt_pass_med_inter', 'mnt_tot_inter_pass', 'nbr_achat_pass_inter',
       'mnt_med_pass_data', 'mnt_tot_pass_data', 'nbr_achat_pass_data',
       'nbr_transac_share', 'vol_tot_data_share', 'vol_moy_data_share',
       'nbr_transac_family', 'vol_tot_data_family', 'vol_moy_data_family',
       'nbr_rechar', 'mnt_rechar_tot', 'mnt_rechar_moy', 'temp_sms_moy',
       'ecartyp_temp_sms', 'nbr_dist_en_of_x', 'nbr_call_en_of_x',
       'duree_call_tot_en_of_x', 'duree_call_moy_en_of_x', 'nbr_dist_sort_on',
       'nbr_call_sort_on', 'duree_call_tot_sort_on', 'duree_call_moy_sort_on',
       'nbr_dist_sort_of', 'nbr_call_sort_of', 'duree_call_tot_sort_of',
       'duree_call_moy_sort_of', 'nbr_sms_tot_sort_inter',
       'nbr_call_tot_sort_inter', 'duree_call_tot_sort_inter',
       'duree_call_moy_sort_inter', 'nbr_call_sort_night',
       'duree_moy_sort_night', 'duree_call_tot_sort_night', 'nbr_sms_tot_en',
       'nbr_dist_sms_en', 'nbr_dist_sort', 'nbr_call_tot_sort',
       'duree_call_tot_sort', 'duree_call_moy_sort', 'nbr_dist_call_en',
       'nbr_call_tot_en', 'duree_call_tot_en', 'duree_call_moy_en',
       'nbre_imsi', 'nbr_dist_en_on', 'nbr_call_en_on', 'duree_call_tot_en_on',
       'duree_call_moy_sort_en', 'nbr_dist_en_of_y', 'nbr_call_en_of_y',
       'duree_call_tot_en_of_y', 'duree_call_moy_en_of_y', 'duree_data_tot',
       'vol_tot_data', 'nbr_call_tot_complice', 'duree_call_moy_complice',
       'duree_call_tot_complice', 'nbr_call_sort_abs', 'nbr_call_en_abs']]

In [63]:
clf = IsolationForest(random_state=0).fit(X)

In [64]:
df_anti2 = df_anti1[['mnt_med_pass_sva', 'mnt_tot_pass_sva', 'nbr_achat_pass_sva',
       'mnt_med_mix', 'mnt_tot_mix', 'nbr_achat_pass_mix',
       'mnt_pass_med_inter', 'mnt_tot_inter_pass', 'nbr_achat_pass_inter',
       'mnt_med_pass_data', 'mnt_tot_pass_data', 'nbr_achat_pass_data',
       'nbr_transac_share', 'vol_tot_data_share', 'vol_moy_data_share',
       'nbr_transac_family', 'vol_tot_data_family', 'vol_moy_data_family',
       'nbr_rechar', 'mnt_rechar_tot', 'mnt_rechar_moy', 'temp_sms_moy',
       'ecartyp_temp_sms', 'nbr_dist_en_of_x', 'nbr_call_en_of_x',
       'duree_call_tot_en_of_x', 'duree_call_moy_en_of_x', 'nbr_dist_sort_on',
       'nbr_call_sort_on', 'duree_call_tot_sort_on', 'duree_call_moy_sort_on',
       'nbr_dist_sort_of', 'nbr_call_sort_of', 'duree_call_tot_sort_of',
       'duree_call_moy_sort_of', 'nbr_sms_tot_sort_inter',
       'nbr_call_tot_sort_inter', 'duree_call_tot_sort_inter',
       'duree_call_moy_sort_inter', 'nbr_call_sort_night',
       'duree_moy_sort_night', 'duree_call_tot_sort_night', 'nbr_sms_tot_en',
       'nbr_dist_sms_en', 'nbr_dist_sort', 'nbr_call_tot_sort',
       'duree_call_tot_sort', 'duree_call_moy_sort', 'nbr_dist_call_en',
       'nbr_call_tot_en', 'duree_call_tot_en', 'duree_call_moy_en',
       'nbre_imsi', 'nbr_dist_en_on', 'nbr_call_en_on', 'duree_call_tot_en_on',
       'duree_call_moy_sort_en', 'nbr_dist_en_of_y', 'nbr_call_en_of_y',
       'duree_call_tot_en_of_y', 'duree_call_moy_en_of_y', 'duree_data_tot',
       'vol_tot_data', 'nbr_call_tot_complice', 'duree_call_moy_complice',
       'duree_call_tot_complice', 'nbr_call_sort_abs', 'nbr_call_en_abs']]

In [72]:
clf.predict(df_anti2.iloc[:300,:])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [73]:
from numpy import unique
clusters_anti = unique(clf.predict(df_anti2.iloc[1:100,:]), return_counts = True)
clusters_anti

(array([1]), array([99]))

In [24]:
df92 = df91

In [25]:
df92["msisdn"] = df["msisdn"]

In [26]:
df6 = df92[df92["classe"] == 6]

In [27]:
df_inner = pd.merge(fraudeurs, df6, on='msisdn', how='inner')

In [28]:
df_inner

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [32]:
for i in df_inner.columns.to_list() :
    if "x" in i :
        df_inner = df_inner.drop([i], axis = 1)

In [33]:
df_inner

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [34]:
df_inner.describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [48]:
kmeans.cluster_centers_

array([[ 5.59497844e+00,  7.60841998e-04,  6.28286837e+02,
         1.49632260e-01,  6.28288359e+02,  1.49632260e-01,
         2.52986905e+02,  8.41491250e-01,  9.23562894e-01,
         8.61273142e-01,  2.97539944e+00,  2.97286330e+00,
         8.59878265e-01,  8.24378666e-01,  7.69464874e-01,
         2.95612478e+00,  2.54450926e+00,  8.41491250e-01,
         1.76008116e+00,  6.18310931e-01,  3.90927213e+02,
         1.38881943e+02,  1.14126300e-01,  6.81942683e+00,
         1.23968988e+04,  9.70327162e-01,  1.24669034e+03,
         1.24669034e+03,  1.14761603e+02,  7.35850154e+07,
         1.99086990e-01,  2.42660064e+08,  1.32386508e+00,
         1.92137966e+01,  1.06644687e-01,  3.93277520e-01,
         1.15433579e+00,  7.47233071e+01,  8.61273142e-01,
         6.66924550e+03,  8.61273142e-01,  1.15433579e+00,
         6.19033731e+02,  6.37966016e-01,  2.50246583e+00,
         1.11771838e+00,  2.81133401e+02,  7.42454984e-01,
         3.08043282e+04,  7.42454984e-01,  1.11771838e+0

In [55]:
from sklearn.ensemble import IsolationForest

In [54]:
df93 = df91[df91["classe"] != 6]

In [57]:
df93 = df93.fillna(0)

In [58]:
clf = IsolationForest(random_state=0).fit(df93)

In [59]:
res = clf.predict(df91[df91["classe"] == 6] )

array([1, 1, 1, ..., 1, 1, 1])

In [61]:
unique(res, return_counts = True)

(array([-1,  1]), array([   2218, 1643389]))

In [63]:
df6["classe_iso"] = res

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3040: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [ ]:
df6[df6["classe_iso"] == -1]

In [67]:
pd.merge(fraudeurs,  df6[df6["classe_iso"] == 1] , on='msisdn', how='inner').shape

(520, 184)

In [36]:
df92 = df9.fillna(0)

In [43]:
kmeanss = KMeans(n_clusters=100, **kmeans_kwargs)
kmeanss.fit(df92)
print(kmeanss.inertia_)

3.6297846454734664e+23


In [44]:
yhatt = kmeanss.predict(df92)

In [45]:
from numpy import unique
unique(yhatt, return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       dtype=int32),
 array([   9316,     112,      12,   11438,       1,       1,     170,
          20365,       1,       1,      52,       1,       1,   24603,
          16943,       1,   15492,       1,     451,       1,       6,
            212,      17,       2,       2,       2,       1,       1,
              3,       8,     258,    4090,      52,       1,     106,
              2,    2714,      16,       1, 1424554,    1722,       4,
              1,    5701,       1,       2,      11,   12507,     106,
          14325,       8,       1

42

In [21]:
df91[df91["classe"] == 4]

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py:345: UserWarning:
Lux defaults to Pandas when there are no valid actions defined.


nbre_call_entrant_inter  nbre_call_sortant_inter  \
1763609                      0.0                      0.0   

         duree_entrant_inter  duree_sortant_inter  duree_total_inter  \
1763609                  0.0                  0.0                0.0   

         duree_moy_sortant_inter  duree_moy_inter  nbr_cor_dist  \
1763609                      0.0              0.0           0.0   

         nbr_appel_abs_entr_moy  nbr_appel_abs_entr_med  ...  temp_appel_moy  \
1763609                     0.0                     0.0  ...             0.0   

         ecartyp_temp_appel  ratio_call_dist  ratio_dist_sms  taux_call_night  \
1763609                 0.0              0.0             0.0              0.0   

         taux_call_on  taux_call_inter  nbre_transaction  \
1763609           0.0              0.0               0.0   

         nbre_distinct_msisdn  classe  
1763609                   0.0       4  

[1 rows x 91 columns]

In [22]:
df99 = df91

In [23]:
df99.index = df["msisdn"]

In [25]:
df99[df99["classe"] == 0]

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [35]:
df999 = df99[df99["classe"] == 6]

In [36]:
kmeanss = KMeans(n_clusters=2, **kmeans_kwargs)
kmeanss.fit(df999)
print(kmeanss.inertia_)

3.8544142700779166e+23


In [37]:
yhatt = kmeanss.predict(df999)

In [38]:
from numpy import unique
clusterss = unique(yhatt, return_counts = True)

In [39]:
clusterss

(array([0, 1], dtype=int32), array([  96188, 1549419]))

In [40]:
df999.shape

(1645607, 91)

In [41]:
df999["classe2"] = yhatt

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3040: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [42]:
df999[df999["classe2"] == 0].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [43]:
df9999 = df999[df999["classe2"] == 1]

In [44]:
kmeanss = KMeans(n_clusters=2, **kmeans_kwargs)
kmeanss.fit(df9999)
print(kmeanss.inertia_)
yhatt = kmeanss.predict(df9999)

from numpy import unique
clusterss = unique(yhatt, return_counts = True)
clusterss

9.772672934336805e+22


(array([0, 1], dtype=int32), array([1549170,     249]))

In [45]:
df9999["classe3"] = yhatt

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3040: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [47]:
df9999[df9999["classe3"] == 1].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [54]:
df999 = df99[df99["nbre_call_sortant_inter"] > 10]

In [97]:
df999999 = df99[df99["nbre_call_sortant_inter"] > 7]

In [98]:
df999999.shape

(24, 91)

In [99]:
df999999.describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [ ]:
kmeanss = KMeans(n_clusters=2, **kmeans_kwargs)
kmeanss.fit(df999)
print(kmeanss.inertia_)

In [94]:
kmeanss = KMeans(n_clusters=2, **kmeans_kwargs)
kmeanss.fit(df999999)
print(kmeanss.inertia_)
yhatt = kmeanss.predict(df999999)

from numpy import unique
clusterss = unique(yhatt, return_counts = True)
clusterss

3.1568156652964055e+22


(array([0, 1], dtype=int32), array([1647,    3]))

In [95]:
df999999["classe2"] = yhatt

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3040: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [96]:
df66[df66["classe2"] == 1].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [81]:
df66[df66["classe2"] == 1]

nbre_call_entrant_inter  nbre_call_sortant_inter  \
msisdn                                                         
77880150.0                      3.0                     10.0   

            duree_entrant_inter  duree_sortant_inter  duree_total_inter  \
msisdn                                                                    
77880150.0                184.0                 39.0              184.0   

            duree_moy_sortant_inter  duree_moy_inter  nbr_cor_dist  \
msisdn                                                               
77880150.0                 5.571429            172.0           1.0   

            nbr_appel_abs_entr_moy  nbr_appel_abs_entr_med  ...  \
msisdn                                                      ...   
77880150.0                     2.0                     2.0  ...   

            ecartyp_temp_appel  ratio_call_dist  ratio_dist_sms  \
msisdn                                                            
77880150.0         6119.550933              0.5        0.657143   

            taux_call_night  taux_call_on  taux_call_inter  nbre_transaction  \
msisdn                                                                         
77880150.0         0.657143      0.840625         0.657143               2.0   

            nbre_distinct_msisdn  classe  classe2  
msisdn                                             
77880150.0                   1.0       6        1  

[1 rows x 92 columns]

In [82]:
df666 = df66[df66["classe2"] == 0]

In [83]:
kmeanss = KMeans(n_clusters=2, **kmeans_kwargs)
kmeanss.fit(df666)
print(kmeanss.inertia_)
yhatt = kmeanss.predict(df666)

from numpy import unique
clusterss = unique(yhatt, return_counts = True)
clusterss

196301647805104.53


(array([0, 1], dtype=int32), array([ 1, 21]))

In [84]:
df666["classe22"] = yhatt

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3040: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [86]:
df666[df666["classe22"] == 1].describe()

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [88]:
df6 = df99[df99["classe"] == 6]

In [ ]:
df68 = df6[df6["classe"] == 6]

In [89]:
kmeanss = KMeans(n_clusters=2, **kmeans_kwargs)
kmeanss.fit(df6)
print(kmeanss.inertia_)
yhatt = kmeanss.predict(df6)

from numpy import unique
clusterss = unique(yhatt, return_counts = True)
clusterss

3.8544142700779166e+23


(array([0, 1], dtype=int32), array([  96188, 1549419]))

In [90]:
df6["classe22"] = yhatt

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3040: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [100]:
df77 = df99[df99["classe"] == 6]

In [106]:
df777 =  df77[df77["nbre_call_sortant_inter"] > 0]

In [104]:
df77[df77["nbre_call_sortant_inter"] > 0].shape

(1516, 91)

In [ ]:
df77[df77["nbre_call_sortant_inter"] > 0]

In [107]:
from sklearn.cluster import SpectralClustering
import numpy as np
X = np.array([[1, 1], [2, 1], [1, 0],
               [4, 7], [3, 5], [3, 6]])
clustering = SpectralClustering(n_clusters=2,
         assign_labels='discretize',
         random_state=0).fit(df777)
clustering.labels_
clustering

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/sklearn/manifold/_spectral_embedding.py:245: UserWarning:Graph is not fully connected, spectral embedding may not work as expected.


SpectralClustering(assign_labels='discretize', n_clusters=2, random_state=0)

In [108]:
silhouette_score(df777, clustering.labels_)

0.07413582948726037

In [110]:
sill : []

In [111]:
for i in range(2,10) :
    clustering = SpectralClustering(n_clusters=i,
         assign_labels='discretize',
         random_state=0).fit(df777)
    sill.append(silhouette_score(df777, clustering.labels_))

/Users/youssouf/opt/anaconda3/lib/python3.8/site-packages/sklearn/manifold/_spectral_embedding.py:245: UserWarning:Graph is not fully connected, spectral embedding may not work as expected.


NameError: name 'sill' is not defined

In [ ]:
plt.style.use("fivethirtyeight")
plt.plot(range(2, 10), sill)
plt.xticks(range(1, 11))
plt.xlabel("Number of Clusters")
plt.ylabel("silhouette_score")
plt.show()