In [1]:
println("Hello Word !!!")

Hello Word !!!


#### Variables

In [3]:
student_name = "Ram"
roll_no = 15
marks_math = 9.5

9.5

In [4]:
student_name

"Ram"

In [6]:
print("www.tutorialspoint.com")

www.tutorialspoint.com

#### Arrays

In [7]:
arr = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

 We can also specify the type and the dimension of an array by using the below syntax −
  - Array{type}(dims)


In [8]:
array = Array{Int64}(undef, 3)

3-element Vector{Int64}:
 4664324400
 4664324432
 4664324464

In [9]:
array = Array{Int64}(undef, 3, 3, 3)

3×3×3 Array{Int64, 3}:
[:, :, 1] =
 4723798032  4723655568  4723797840
 4723798032  4723655568  4723655568
 4723798032  4723797840  4723655568

[:, :, 2] =
 4723655568  4723655568  4723797840
 4723655568  4723655568  4723797840
 4723797840  4723797840  4723655568

[:, :, 3] =
 4723723216  4723797840  4723655568
 4723655568  4723797840  4723798032
 4723655568  4723655568  4723655568

Here we placed the type in curly braces and the dimensions in parentheses. 
We use undef which means that particular array has not been initialized to any known value and thats why we got random numbers in the output.

##### Arrays of anything

In [11]:
a = [1, "TutorialsPoint.com", 5.5, tan, pi]

5-element Vector{Any}:
 1
  "TutorialsPoint.com"
 5.5
  tan (generic function with 12 methods)
 π = 3.1415926535897...

##### Empty Arrays

In [12]:
A = Int64[]

B = String[]

String[]

#### Creating 2D arrays & matrices

Leave out the comma between elements and you will be getting 2D arrays in Julia. Below is the example given for single row, multi-column array −

In [14]:
# Here, 1×10 is the first row of this array.
[1 2 3 4 5 6 7 8 9 10]

1×10 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10

To add another row, just add a semicolon(;). Let us check the below example −

In [16]:
# Here, it becomes 2×5 array.
[1 2 3 4 5 ; 6 7 8 9 10]

2×5 Matrix{Int64}:
 1  2  3  4   5
 6  7  8  9  10

##### Creating arrays using range objects

First useful function to create an array using range objects is collect(). With the help of colon(:) and **collect()** function, we can create an array using range objects as follows −

In [17]:
collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [18]:
# We can also create arrays with floating point range objects −
collect(1.5:5.5)

5-element Vector{Float64}:
 1.5
 2.5
 3.5
 4.5
 5.5

In [19]:
# Below is an example to build an array with elements that go from 0 to 50 in steps of 5 −
collect(0:5:50)

11-element Vector{Int64}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50

In [1]:
# Instead of using collect() function, we can also use splat operator or ellipsis(…) after the last element
[0:10...]

11-element Vector{Int64}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

#### range() function

Range() is another useful function to create an array with range objects. It goes from start value to end value by taking a specific step value.

For example, let us see an example to go from 1 to 150 in exactly 15 steps −

In [2]:
range(1, length=15, stop=150)

1.0:10.642857142857142:150.0

In [3]:
range(1, stop=150, step=10)

1:10:141

We can use range() with collect() to build an array as follows −

In [4]:
collect(range(1, length=15, stop=150))

15-element Vector{Float64}:
   1.0
  11.642857142857142
  22.285714285714285
  32.92857142857143
  43.57142857142857
  54.214285714285715
  64.85714285714286
  75.5
  86.14285714285714
  96.78571428571429
 107.42857142857143
 118.07142857142857
 128.71428571428572
 139.35714285714286
 150.0

#### Creating arrays using comprehensions and generators

In [5]:
[n^2 for n in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [6]:
# We can easily create a 2-D array also as follows −
[n*m for n in 1:10, m in 1:10]

10×10 Matrix{Int64}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

In [7]:
# Similar to comprehension, we can use generator expressions to create an array −
collect(n^2 for n in 1:5)

5-element Vector{Int64}:
  1
  4
  9
 16
 25

#### Populating an Array

In [8]:
zeros(4,5)

4×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [9]:
# We can also specify the type of zeros as follows −
zeros(Int64,4,5)

4×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [10]:
ones(4,5)

4×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [11]:
rand(4,5)

4×5 Matrix{Float64}:
 0.789607  0.722711   0.907251   0.320397    0.68407
 0.985867  0.0836461  0.666863   0.676358    0.3993
 0.10569   0.302893   0.062831   0.00167796  0.594234
 0.350661  0.714231   0.0155535  0.107549    0.490105

In [12]:
# As the name suggests, this function will create m*n matrix of normally distributed random numbers 
# with mean=0 and standard deviation(SD)=1
randn(m, n)

LoadError: UndefVarError: m not defined

In [13]:
# This function is used to fill an array with a specific value. 
# More specifically, it will create an array of repeating duplicate value.
fill(100,5)

5-element Vector{Int64}:
 100
 100
 100
 100
 100

#### Copying arrays

In [14]:
A = collect(1:5);
B = similar(A)

5-element Vector{Int64}:
 4449230000
 4449230032
 4449238928
 4449240208
 4449231856

#### Accessing the contents of arrays

In [15]:
arr = [5,10,15,20,25,30,35,40,45,50]
arr[4]

20

In [16]:
arr[1]

5

In [17]:
arr[end]

50

In [18]:
arr[[true, false, true, true,true, false, false, true, true, false]]

6-element Vector{Int64}:
  5
 15
 20
 25
 40
 45

In [19]:
arr2 = [10 11 12; 13 14 15; 16 17 18]

3×3 Matrix{Int64}:
 10  11  12
 13  14  15
 16  17  18

In [20]:
arr2[1]

10

In [21]:
arr2[1,2]

11

In [22]:
arr2[1,3]

12

In [23]:
# We can also use getindex() function to obtain elements from a 2-D array −
getindex(arr2,1,2)

11

In [24]:
getindex(arr2,2,3)

15

#### Adding Elements

In [ ]:
# We can add elements to an array in Julia at the end, at the front and at the given index using 
# push!(), pushfirst!() and splice!() functions respectively.



In [25]:
# At the end
push!(arr,55)

11-element Vector{Int64}:
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

In [26]:
# At the front
pushfirst!(arr,0)

12-element Vector{Int64}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

In [27]:
# At a given index
splice!(arr,2:5,2:6)

4-element Vector{Int64}:
  5
 10
 15
 20

#### Removing Elements

We can remove elements at last position, first position and at the given index, from an array in Julia, using **pop!()** , **popfirst!()** and **splice!()** functions respectively.

In [28]:
# Remove the last element
pop!(arr)

55

In [29]:
# Removing the first element
popfirst!(arr)

0

In [30]:
# Removing element at given position
splice!(arr,5)

6